# Multi-Crisis

Domain Adaptation with Adversarial Training and Graph Embeddings

---

## A. Original description

## B. Overview

In [1]:
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
datasets_path = Path(os.getenv("DATASETS_PATH")) / "Datasets"

In [2]:
import pandas as pd

dataset_path = datasets_path / 'Multi_Crisis'

files = [
    'Subset_Data_Uniques_LF_no_text.csv',
    'Subset_Not_related_tweets_no_text.csv',
    'Unified_MultiCrisis_Dataset_no_text.csv',
]

### Subset_Data_Uniques_LF_no_text

In [ ]:
filepath = dataset_path / files[0]

if not filepath.exists():
    raise FileNotFoundError(f'Not found: {filepath}')

df_1 = pd.read_csv(filepath)
df_1.columns = df_1.columns.str.strip()

In [4]:
df_1.head()

,tweet_id,dataset,crisis,country,year,lan_final,hazard_type,hazard_cat,hazard_subcat,development,...,SCONJ,SYM,VERB,X,I-LOC,I-ORG,I-PER,has__I-LOC,has__I-ORG,has__I-PER
0,9751718855,ChileEarthquakeT1,earthquake_Chile,Chile,2010,es,earthquake,natural,geophysical,instantaneous,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0,0,1
1,9797202566,ChileEarthquakeT1,earthquake_Chile,Chile,2010,es,earthquake,natural,geophysical,instantaneous,...,0.0,0.0,1.0,3.0,1.0,0.0,0.0,1,0,0
2,9797126085,ChileEarthquakeT1,earthquake_Chile,Chile,2010,es,earthquake,natural,geophysical,instantaneous,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0,0,0
3,9796989900,ChileEarthquakeT1,earthquake_Chile,Chile,2010,es,earthquake,natural,geophysical,instantaneous,...,2.0,0.0,1.0,2.0,0.0,0.0,0.0,0,0,0
4,9756501365,ChileEarthquakeT1,earthquake_Chile,Chile,2010,es,earthquake,natural,geophysical,instantaneous,...,0.0,0.0,3.0,3.0,0.0,0.0,1.0,0,0,1

### Subset_Not_related_tweets_no_text

In [5]:
filepath = dataset_path / files[1]

if not filepath.exists():
    raise FileNotFoundError(f'Not found: {filepath}')

df_2 = pd.read_csv(filepath)
df_2.columns = df_2.columns.str.strip()

In [6]:
df_2.head()

,tweet_id,dataset,crisis,country,year,lan_final,hazard_type,hazard_cat,hazard_subcat,development,...,SCONJ,SYM,VERB,X,I-LOC,I-ORG,I-PER,has__I-LOC,has__I-ORG,has__I-PER
0,211040709124440064,CrisisLexT26,wildfires_Colorado,EEUU,2012,es,wildfires,natural,climatological,progressive,...,0.0,1.0,0.0,4.0,6.0,0.0,0.0,1,0,0
1,211111710294163457,CrisisLexT26,wildfires_Colorado,EEUU,2012,es,wildfires,natural,climatological,progressive,...,0.0,0.0,1.0,9.0,1.0,0.0,0.0,1,0,0
2,211157222699433985,CrisisLexT26,wildfires_Colorado,EEUU,2012,es,wildfires,natural,climatological,progressive,...,0.0,0.0,1.0,6.0,1.0,1.0,1.0,1,1,1
3,211162553659830272,CrisisLexT26,wildfires_Colorado,EEUU,2012,es,wildfires,natural,climatological,progressive,...,0.0,0.0,1.0,2.0,0.0,1.0,1.0,0,1,1
4,324199955197734912,CrisisLexT6,bombing_Boston,EEUU,2013,es,bombings,human_induced,intentional,instantaneous,...,0.0,0.0,1.0,12.0,0.0,0.0,0.0,0,0,0

### Unified_MultiCrisis_Dataset_no_text

In [7]:
filepath = dataset_path / files[2]

if not filepath.exists():
    raise FileNotFoundError(f'Not found: {filepath}')

df_3 = pd.read_csv(filepath)
df_3.columns = df_3.columns.str.strip()

In [8]:
df_3.head()

,tweet_id,dataset,crisis,country,year,original_label,mapped_label,hazard_type,hazard_cat,hazard_subcat,development,spread,vote_lan,lan_final
0,9725643670,ChileEarthquakeT1,earthquake_Chile,Chile,2010,True,Related,earthquake,natural,geophysical,instantaneous,diffused,"[('es', 3)]",es
1,9725759250,ChileEarthquakeT1,earthquake_Chile,Chile,2010,True,Related,earthquake,natural,geophysical,instantaneous,diffused,"[('es', 3)]",es
2,9725877906,ChileEarthquakeT1,earthquake_Chile,Chile,2010,False,Not_Related,earthquake,natural,geophysical,instantaneous,diffused,"[('es', 3)]",es
3,9726077826,ChileEarthquakeT1,earthquake_Chile,Chile,2010,False,Not_Related,earthquake,natural,geophysical,instantaneous,diffused,"[('es', 3)]",es
4,9721410480,ChileEarthquakeT1,earthquake_Chile,Chile,2010,False,Not_Related,earthquake,natural,geophysical,instantaneous,diffused,"[('es', 2), ('ca', 1)]",es