# Non-related Datasets

In real world, non-related tweets are dominant to related. This notebook gathers other twitter datasets for the simulation.

## A. Overview

List of datasets

| No | Name | Num of Records | Note |
| - | - | - | - |
| 1 | Sanders Analytics Sentiment-labelled tweets  | 0 | out-topic |
| 2 | 2015-new-years-resolutions | 0 | out-topic |
| 3 | Depression: Twitter Dataset + Feature Extraction | 0 | out-topic |
| 4 | Customer Support on Twitter | 0 | out-topic |
| 5 | Twitter Sentiment Dataset | 0 | noise |
| 6 | Twitter Toxic Tweets | 0 | out-topic |
| 7 | Sentiment140 | 0 | Noise - Too big |
| 8 | twitter_cikm_2010 | 0 | Noise - Too big |
| 9 | Sentiment of Climate Change | 0 | closed-topic |
| 10 | Twitter Climate Change Sentiment Dataset | 0 | closed-topic |
| 11 | Weather sentiment evaluated | 0 | closed-topic |

In [2]:
from pathlib import Path
import os
import random
import csv

import numpy as np

import pandas as pd

import configuration
from src import setup, data_utils

random.seed(setup.RANDOM_SEED)

from dotenv import load_dotenv

load_dotenv()

# dataset_path = Path(os.getenv("DATASETS_PATH")) / "Datasets for Balancing"

True

In [2]:
def load_dataset(
    dataset: str,
    file: str,
    headers: list[str] = [],
    sep: str = ",",
    encoding: str = "utf-8",
    print_head: bool = True,
    map_columns: dict[str, str] = {},
    frac: float = 1.0,
) -> pd.DataFrame:
    filepath = dataset_path / dataset / file
    df = pd.read_csv(
        filepath,
        sep=sep,
        encoding=encoding,
        names=headers if headers else None,
        on_bad_lines="skip",
    )
    if print_head:
        print(f"Shape {df.shape}")
        print(f"Original:")
        display(df.head())

    # Rename columns if mapping is provided and select only the mapped columns
    if map_columns:
        df = df.rename(columns=map_columns)[list(map_columns.values())]

    # Sample the dataset if frac < 1.0
    if frac < 1.0:
        df = df.sample(frac=frac, random_state=setup.RANDOM_SEED)
        print(f"Fraction Shape {df.shape}")

    df["dataset"] = dataset

    if print_head:
        display(df.head())
    return df

### A.1. Sanders Analytics Sentiment-labelled tweets

In [3]:
df_1 = load_dataset(
    dataset="Sanders Analytics Sentiment-labelled tweets",
    file="full-corpus.csv",
    map_columns={"TweetText": "tweet_text"},
)

# The dataset contains tweets about 4 companies: Microsoft, Google, Twitter, and Apple.
# df_1['Topic'].value_counts()
# microsoft    1364
# google       1317
# twitter      1290
# apple        1142

companies = ["microsoft", "google", "twitter", "apple"]
for company in companies:
    # remove @company from the text
    df_1["tweet_text"] = df_1["tweet_text"].str.replace(
        f"@{company}", "@USER", case=False
    )
df_1.head()

Shape (5113, 5)
Original:

,Topic,Sentiment,TweetId,TweetDate,TweetText
0,apple,positive,126415614616154112,Tue Oct 18 21:53:25 +0000 2011,Now all @Apple has to do is get swype on the i...
1,apple,positive,126404574230740992,Tue Oct 18 21:09:33 +0000 2011,@Apple will be adding more carrier support to ...
2,apple,positive,126402758403305474,Tue Oct 18 21:02:20 +0000 2011,Hilarious @youtube video - guy does a duet wit...
3,apple,positive,126397179614068736,Tue Oct 18 20:40:10 +0000 2011,@RIM you made it too easy for me to switch to ...
4,apple,positive,126395626979196928,Tue Oct 18 20:34:00 +0000 2011,I just realized that the reason I got into twi...

,tweet_text,dataset
0,Now all @Apple has to do is get swype on the i...,Sanders Analytics Sentiment-labelled tweets
1,@Apple will be adding more carrier support to ...,Sanders Analytics Sentiment-labelled tweets
2,Hilarious @youtube video - guy does a duet wit...,Sanders Analytics Sentiment-labelled tweets
3,@RIM you made it too easy for me to switch to ...,Sanders Analytics Sentiment-labelled tweets
4,I just realized that the reason I got into twi...,Sanders Analytics Sentiment-labelled tweets

,tweet_text,dataset
0,Now all @USER has to do is get swype on the ip...,Sanders Analytics Sentiment-labelled tweets
1,@USER will be adding more carrier support to t...,Sanders Analytics Sentiment-labelled tweets
2,Hilarious @youtube video - guy does a duet wit...,Sanders Analytics Sentiment-labelled tweets
3,@RIM you made it too easy for me to switch to ...,Sanders Analytics Sentiment-labelled tweets
4,I just realized that the reason I got into twi...,Sanders Analytics Sentiment-labelled tweets

### A.2. 2015-new-years-resolutions

In [4]:
df_2 = load_dataset(
    dataset="2015-new-years-resolutions",
    file="New-years-resolutions-DFE.csv",
    encoding="latin-1",
    map_columns={"text": "tweet_text"},
)

Shape (5011, 15)
Original:

,other_topic,resolution_topics,gender,name,Resolution_Category,retweet_count,text,tweet_coord,tweet_created,tweet_date,tweet_id,tweet_location,tweet_state,user_timezone,tweet_region
0,"Read moore books, read less facebook.",Eat healthier,female,Dena_Marina,Health & Fitness,0.0,"#NewYearsResolution :: Read more books, No scr...",NaN,12/31/14 10:48,12/31/14,5.503630e+17,Southern California,CA,Pacific Time (US & Canada),West
1,NaN,Humor about Personal Growth and Interests Reso...,female,ninjagirl325,Humor,1.0,#NewYearsResolution Finally master @ZJ10 's pa...,NaN,12/31/14 10:47,12/31/14,5.503630e+17,New Jersey,NJ,Central Time (US & Canada),Northeast
2,NaN,Be More Confident,male,RickyDelReyy,Personal Growth,0.0,#NewYearsResolution to stop being so damn perf...,NaN,12/31/14 10:46,12/31/14,5.503620e+17,Hollywood,CA,Eastern Time (US & Canada),West
3,Help More\nspread pet therapy|helping other,Other,male,CalmareNJ,Philanthropic,0.0,My #NewYearsResolution is to help my disabled ...,NaN,12/31/14 10:45,12/31/14,5.503620e+17,Metro NYC,NY,NaN,Northeast
4,NaN,Be more positive,female,welovatoyoudemi,Personal Growth,0.0,#NewYearsResolution #2015Goals #2015bucketlist...,NaN,12/31/14 10:44,12/31/14,5.503620e+17,"Pittsburgh, Pennsylvania",PA,Eastern Time (US & Canada),Northeast

,tweet_text,dataset
0,"#NewYearsResolution :: Read more books, No scr...",2015-new-years-resolutions
1,#NewYearsResolution Finally master @ZJ10 's pa...,2015-new-years-resolutions
2,#NewYearsResolution to stop being so damn perf...,2015-new-years-resolutions
3,My #NewYearsResolution is to help my disabled ...,2015-new-years-resolutions
4,#NewYearsResolution #2015Goals #2015bucketlist...,2015-new-years-resolutions

### A.3. Depression: Twitter Dataset + Feature Extraction

In [5]:
df_3 = load_dataset(
    dataset="Depression - Twitter Dataset + Feature Extraction",
    file="Mental-Health-Twitter.csv",
    map_columns={"post_text": "tweet_text"},
)

Shape (20000, 11)
Original:

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1

,tweet_text,dataset
0,It's just over 2 years since I was diagnosed w...,Depression - Twitter Dataset + Feature Extraction
1,"It's Sunday, I need a break, so I'm planning t...",Depression - Twitter Dataset + Feature Extraction
2,Awake but tired. I need to sleep but my brain ...,Depression - Twitter Dataset + Feature Extraction
3,RT @SewHQ: #Retro bears make perfect gifts and...,Depression - Twitter Dataset + Feature Extraction
4,It’s hard to say whether packing lists are mak...,Depression - Twitter Dataset + Feature Extraction

### A.4. Customer Support on Twitter

In [6]:
# FULL DATASET
dataset_4 = "Customer Support on Twitter"
file_4 = "twcs/twcs.csv"

# # SAMPLE DATASET
# dataset_4 = 'Customer Support on Twitter'
# file_4 = 'sample.csv'

df_4 = load_dataset(
    dataset=dataset_4,
    file=file_4,
    map_columns={"text": "tweet_text", "author_id": "author_id"},
    frac=0.1,  # sample 10% of the dataset to speed up processing
)

# replace @author_id with @USER in the text
df_4["tweet_text"] = df_4.apply(
    lambda row: row["tweet_text"].replace(f"@{row['author_id']}", "@USER"), axis=1
)
df_4.drop(columns=["author_id"], inplace=True)
df_4.head()

Shape (2811774, 7)
Original:

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

Fraction Shape (281177, 2)

,tweet_text,author_id,dataset
160535,@161252 What's that egg website people talk about,161253,Customer Support on Twitter
659248,Why!🤷🏻‍♀️ #iOS11 @AppleSupport https://t.co/BX...,296574,Customer Support on Twitter
2250310,@693975 We can assist you. We recommend updati...,AppleSupport,Customer Support on Twitter
1640680,@331912 @115955 Thats better than having an un...,539096,Customer Support on Twitter
1933623,@VirginAmerica is probably one of the best air...,617376,Customer Support on Twitter

,tweet_text,dataset
160535,@161252 What's that egg website people talk about,Customer Support on Twitter
659248,Why!🤷🏻‍♀️ #iOS11 @AppleSupport https://t.co/BX...,Customer Support on Twitter
2250310,@693975 We can assist you. We recommend updati...,Customer Support on Twitter
1640680,@331912 @115955 Thats better than having an un...,Customer Support on Twitter
1933623,@VirginAmerica is probably one of the best air...,Customer Support on Twitter

### A.5. Twitter Sentiment Dataset

In [7]:
df_5 = load_dataset(
    dataset="Twitter Sentiments Dataset",
    file="Twitter_Data.csv",
    map_columns={"clean_text": "tweet_text"},
)

Shape (162980, 2)
Original:

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

,tweet_text,dataset
0,when modi promised “minimum government maximum...,Twitter Sentiments Dataset
1,talk all the nonsense and continue all the dra...,Twitter Sentiments Dataset
2,what did just say vote for modi welcome bjp t...,Twitter Sentiments Dataset
3,asking his supporters prefix chowkidar their n...,Twitter Sentiments Dataset
4,answer who among these the most powerful world...,Twitter Sentiments Dataset

### A.6. Twitter Toxic Tweets

In [8]:
df_6 = load_dataset(
    dataset="Twitter Toxic Tweets",
    file="twitter_toxic_tweets.csv",
    map_columns={"tweet": "tweet_text"},
)

Shape (31962, 3)
Original:

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

                                          tweet_text               dataset
0   @user when a father is dysfunctional and is s...  Twitter Toxic Tweets
1  @user @user thanks for #lyft credit i can't us...  Twitter Toxic Tweets
2                                bihday your majesty  Twitter Toxic Tweets
3  #model   i love u take with u all the time in ...  Twitter Toxic Tweets
4             factsguide: society now    #motivation  Twitter Toxic Tweets

### A.7. Sentiment140
Large dataset

In [9]:
df_7 = load_dataset(
    dataset="Sentiment140",
    file="training.1600000.processed.noemoticon.csv",
    encoding="latin-1",
    headers=["target", "id", "date", "flag", "user", "text"],
    map_columns={"text": "tweet_text"},
)

Shape (1600000, 6)
Original:

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

                                          tweet_text       dataset
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  Sentiment140
1  is upset that he can't update his Facebook by ...  Sentiment140
2  @Kenichan I dived many times for the ball. Man...  Sentiment140
3    my whole body feels itchy and like its on fire   Sentiment140
4  @nationwideclass no, it's not behaving at all....  Sentiment140

### A.8. twitter_cikm_2010

In [10]:
headers_8 = ["UserID", "TweetID", "Tweet", "CreatedAt"]
dataset_8 = "twitter_cikm_2010"

# FULL DATASET
test_file = "test_set_tweets.txt"
train_file = "training_set_tweets.txt"

# # SAMPLE DATASET
# test_file ='test_set_tweets_sample.txt'
# train_file = 'training_set_tweets_sample.txt'

In [11]:
df_8_test = load_dataset(
    dataset=dataset_8,
    file=test_file,
    sep="\t",
    headers=headers_8,
    map_columns={"Tweet": "tweet_text"},
)

Shape (5135949, 4)
Original:

,UserID,TweetID,Tweet,CreatedAt
0,22077441,10538487904,Ok today I have to find something to wear for ...,2010-03-15 17:35:58
1,22077441,10536835844,I am glad I'm having this show but I can't wai...,2010-03-15 16:53:44
2,22077441,10536809086,Honestly I don't even know what's going on any...,2010-03-15 16:52:59
3,22077441,10534149786,@LovelyJ_Janelle hey sorry I'm sitting infront...,2010-03-15 15:42:07
4,22077441,10530203659,Sitting infront of this sewing machine ... I d...,2010-03-15 13:55:22

                                          tweet_text            dataset
0  Ok today I have to find something to wear for ...  twitter_cikm_2010
1  I am glad I'm having this show but I can't wai...  twitter_cikm_2010
2  Honestly I don't even know what's going on any...  twitter_cikm_2010
3  @LovelyJ_Janelle hey sorry I'm sitting infront...  twitter_cikm_2010
4  Sitting infront of this sewing machine ... I d...  twitter_cikm_2010

In [12]:
df_8_train = load_dataset(
    dataset=dataset_8,
    file=train_file,
    sep="\t",
    headers=headers_8,
    map_columns={"Tweet": "tweet_text"},
)

Shape (3807585, 4)
Original:

/var/folders/yh/9qq7z2f14f14bdj_1k2673700000gn/T/ipykernel_51510/763725202.py:12: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,UserID,TweetID,Tweet,CreatedAt
0,60730027,6320951896,@thediscovietnam coo. thanks. just dropped yo...,2009-12-03 18:41:07
1,60730027,6320673258,@thediscovietnam shit it ain't lettin me DM yo...,2009-12-03 18:31:01
2,60730027,6319871652,"@thediscovietnam hey cody, quick question...ca...",2009-12-03 18:01:51
3,60730027,6318151501,@smokinvinyl dang. you need anything? I got ...,2009-12-03 17:00:16
4,60730027,6317932721,"maybe i'm late in the game on this one, but th...",2009-12-03 16:52:36

                                          tweet_text            dataset
0  @thediscovietnam coo.  thanks. just dropped yo...  twitter_cikm_2010
1  @thediscovietnam shit it ain't lettin me DM yo...  twitter_cikm_2010
2  @thediscovietnam hey cody, quick question...ca...  twitter_cikm_2010
3  @smokinvinyl dang.  you need anything?  I got ...  twitter_cikm_2010
4  maybe i'm late in the game on this one, but th...  twitter_cikm_2010

### A.9. Sentiment of Climate Change

In [13]:
df_9 = load_dataset(
    dataset="Sentiment of Climate Change",
    file="1377884570_tweet_global_warming.csv",
    map_columns={"tweet": "tweet_text"},
)

Shape (6090, 3)
Original:

,tweet,existence,existence.confidence
0,Global warming report urges governments to act...,Yes,1.0000
1,Fighting poverty and global warming in Africa ...,Yes,1.0000
2,Carbon offsets: How a Vatican forest failed to...,Yes,0.8786
3,Carbon offsets: How a Vatican forest failed to...,Yes,1.0000
4,URUGUAY: Tools Needed for Those Most Vulnerabl...,Yes,0.8087

,tweet_text,dataset
0,Global warming report urges governments to act...,Sentiment of Climate Change
1,Fighting poverty and global warming in Africa ...,Sentiment of Climate Change
2,Carbon offsets: How a Vatican forest failed to...,Sentiment of Climate Change
3,Carbon offsets: How a Vatican forest failed to...,Sentiment of Climate Change
4,URUGUAY: Tools Needed for Those Most Vulnerabl...,Sentiment of Climate Change

### A.10. Twitter Climate Change Sentiment Dataset

In [14]:
df_10 = load_dataset(
    dataset="Twitter Climate Change Sentiment Dataset",
    file="twitter_sentiment_data.csv",
    map_columns={"message": "tweet_text"},
)

Shape (43943, 3)
Original:

,sentiment,message,tweetid
0,-1,@tiniebeany climate change is an interesting h...,792927353886371840
1,1,RT @NatGeoChannel: Watch #BeforeTheFlood right...,793124211518832641
2,1,Fabulous! Leonardo #DiCaprio's film on #climat...,793124402388832256
3,1,RT @Mick_Fanning: Just watched this amazing do...,793124635873275904
4,2,"RT @cnalive: Pranita Biswasi, a Lutheran from ...",793125156185137153

,tweet_text,dataset
0,@tiniebeany climate change is an interesting h...,Twitter Climate Change Sentiment Dataset
1,RT @NatGeoChannel: Watch #BeforeTheFlood right...,Twitter Climate Change Sentiment Dataset
2,Fabulous! Leonardo #DiCaprio's film on #climat...,Twitter Climate Change Sentiment Dataset
3,RT @Mick_Fanning: Just watched this amazing do...,Twitter Climate Change Sentiment Dataset
4,"RT @cnalive: Pranita Biswasi, a Lutheran from ...",Twitter Climate Change Sentiment Dataset

### A.11. Weather sentiment evaluated

In [15]:
df_11 = load_dataset(
    dataset="Weather sentiment evaluated",
    file="weather-evaluated-agg-DFE.csv",
    map_columns={"tweet_text": "tweet_text"},
)

Shape (1000, 18)
Original:

,_unit_id,_golden,_canary,_unit_state,_trusted_judgments,_last_judgment_at,is_the_category_correct_for_this_tweet,is_the_category_correct_for_this_tweet:confidence,orig__canary,orig__last_judgment_at,orig__trusted_judgments,orig__unit_id,orig__unit_state,gold_answer,sentiment,tweet_id,tweet_text,what_emotion_does_the_author_express_specifically_about_the_weatherconfidence
0,315120690,True,NaN,golden,98,NaN,Yes,1.0000,NaN,8/24/13 0:21,20,1,finalized,Yes,Positive,81990560,Grilling kabobs on the grill last night was am...,0.8439
1,315120691,True,NaN,golden,78,NaN,Yes,1.0000,NaN,8/24/13 0:49,20,1,finalized,Yes,Negative,84314377,The slowest day ever !! And the weather makes ...,0.6963
2,315120692,True,NaN,golden,62,NaN,Yes,1.0000,NaN,8/24/13 0:55,20,1,finalized,Yes,Neutral / author is just sharing information,82846118,Fire Weather Watch issued May 17 at 4:21PM CDT...,0.8802
3,315120693,True,NaN,golden,68,NaN,Yes,1.0000,NaN,8/24/13 0:48,20,1,finalized,Yes,Positive,82843785,Im going to lunch early today. The weather i...,0.6897
4,315120694,True,NaN,golden,64,NaN,Yes,0.9239,NaN,8/24/13 1:19,20,1,finalized,Yes,Neutral / author is just sharing information,82840144,Weekend Weather Causes Delays In I-270 Bridge ...,0.6153

,tweet_text,dataset
0,Grilling kabobs on the grill last night was am...,Weather sentiment evaluated
1,The slowest day ever !! And the weather makes ...,Weather sentiment evaluated
2,Fire Weather Watch issued May 17 at 4:21PM CDT...,Weather sentiment evaluated
3,Im going to lunch early today. The weather i...,Weather sentiment evaluated
4,Weekend Weather Causes Delays In I-270 Bridge ...,Weather sentiment evaluated

## B. Unified all Dataset

In [16]:
# disaster_path = Path.cwd().parent / "data" / "extended"
disaster_path = Path('..') / "data" / "extended"
disaster_path.mkdir(parents=True, exist_ok=True)

### B.1. Combine

In [17]:
df_out = pd.concat(
    [df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8_train, df_8_test], ignore_index=True
).dropna().drop_duplicates(subset=["tweet_text"], keep="first")
df_out.shape

(10696773, 2)

In [18]:
df_weather = pd.concat([df_9, df_10, df_11], ignore_index=True).dropna().drop_duplicates(subset=["tweet_text"], keep="first")
df_weather.shape

(47573, 2)

### B.2. Filter Single tokens

In [19]:
# remove tweets with less than 3 words or hashtags only
df_weather = df_weather[df_weather['tweet_text'].str.split().str.len() >= 3]
df_out = df_out[df_out['tweet_text'].str.split().str.len() >= 3]

In [ ]:
print(df_weather.shape)
print(df_out.shape)

(47518, 2)
(10403525, 2)

### B.3. Export

In [15]:
disaster_count = 244403 # number of tweets in the disaster dataset
idx = disaster_count + 1
# add uid - `unique identifier` column
df_weather.insert(0, 'uid', range(idx, len(df_weather) + idx))
df_weather.head()

,uid,tweet_text,dataset
0,244404,Global warming report urges governments to act...,Sentiment of Climate Change
1,244405,Fighting poverty and global warming in Africa ...,Sentiment of Climate Change
2,244406,Carbon offsets: How a Vatican forest failed to...,Sentiment of Climate Change
3,244407,URUGUAY: Tools Needed for Those Most Vulnerabl...,Sentiment of Climate Change
4,244408,RT @sejorg: RT @JaymiHeimbuch: Ocean Saltiness...,Sentiment of Climate Change

In [16]:
# add uid - `unique identifier` column
idx = disaster_count + len(df_weather) + 1
df_out.insert(0, 'uid', range(idx, len(df_out) + idx))
df_out.head()

,uid,tweet_text,dataset
0,291922,Now all @USER has to do is get swype on the ip...,Sanders Analytics Sentiment-labelled tweets
1,291923,@USER will be adding more carrier support to t...,Sanders Analytics Sentiment-labelled tweets
2,291924,Hilarious @youtube video - guy does a duet wit...,Sanders Analytics Sentiment-labelled tweets
3,291925,@RIM you made it too easy for me to switch to ...,Sanders Analytics Sentiment-labelled tweets
4,291926,I just realized that the reason I got into twi...,Sanders Analytics Sentiment-labelled tweets

In [17]:
df_out.to_csv(disaster_path / "out_topic.csv", index=False, quoting=csv.QUOTE_NONNUMERIC)
df_weather.to_csv(disaster_path / "weather.csv", index=False, quoting=csv.QUOTE_NONNUMERIC)

### B.4. Samples

In [ ]:
# Load saved datasets from file if do not want to run the above code again
disaster_path = Path('..') / "data" / "extended"
df_out = pd.read_csv(disaster_path / "out_topic.csv")
df_weather = pd.read_csv(disaster_path / "weather.csv")

In [5]:
frac_out = data_utils.get_data_out_topic_fraction()
out_path = disaster_path / str(frac_out)
out_path.mkdir(parents=True, exist_ok=True)
df_out_sample = df_out.sample(frac=frac_out, random_state=setup.RANDOM_SEED).reset_index(drop=True)
df_out_sample.to_csv(out_path / "out_topic.csv", index=False, quoting=csv.QUOTE_ALL)

print(f"Sampling {frac_out:.2%} ({df_out_sample.shape[0]} rows) of the dataset for out-topic data...")

del df_out_sample

Sampling 0.03% (3225 rows) of the dataset for out-topic data...

In [6]:
frac_weather = data_utils.get_data_weather_fraction()
path_weather = disaster_path / str(frac_weather)
path_weather.mkdir(parents=True, exist_ok=True)
df_weather_sample = df_weather.sample(frac=frac_weather, random_state=setup.RANDOM_SEED).reset_index(drop=True)
df_weather_sample.to_csv(path_weather / f"weather.csv", index=False, quoting=csv.QUOTE_ALL)

print(f"Sampling {frac_weather:.2%} ({df_weather_sample.shape[0]} rows) of the dataset for weather data...")

del df_weather_sample

Sampling 10.00% (4752 rows) of the dataset for weather data...