# Non-related Datasets

In real world, non-related tweets are dominant to related. This notebook gathers other twitter datasets for the simulation.

## A. Overview

List of datasets

| No | Name | Num of Records | Note |
| - | - | - | - |
| 1 | Sanders Analytics Sentiment-labelled tweets  | 0 | out-topic |
| 2 | 2015-new-years-resolutions | 0 | out-topic |
| 3 | Depression: Twitter Dataset + Feature Extraction | 0 | out-topic |
| 4 | Customer Support on Twitter | 0 | out-topic |
| 5 | Twitter Sentiment Dataset | 0 | noise |
| 6 | Twitter Toxic Tweets | 0 | out-topic |
| 7 | Sentiment140 | 0 | Noise - Too big |
| 8 | twitter_cikm_2010 | 0 | Noise - Too big |
| 9 | Sentiment of Climate Change | 0 | closed-topic |
| 10 | Twitter Climate Change Sentiment Dataset | 0 | closed-topic |
| 11 | Weather sentiment evaluated | 0 | closed-topic |

In [ ]:
from pathlib import Path
import os

import numpy as np
import pandas as pd

import configuration
from src import dataset_settings, config

from dotenv import load_dotenv
load_dotenv()

dataset_path = Path(os.getenv("DATASETS_PATH")) / 'Datasets for Balancing'

In [66]:
def load_dataset(
    filepath: Path,
    map_columns: dict[str, str] = {},
    sep: str = ",",
    encoding: str = "utf-8",
    print_head: bool = True,
    headers: list[str] = [],
    frac: float = 1.0,
) -> pd.DataFrame:
    df = pd.read_csv(filepath, sep=sep, encoding=encoding, names=headers if headers else None, on_bad_lines='skip')
    print(f"Shape {df.shape}")
    if map_columns:
        df = df.rename(columns=map_columns)[list(map_columns.values())]
    if print_head:
        display(df.head())
    if frac < 1.0:
        df = df.sample(frac=frac, random_state=config.RANDOM_SEED)
        print(f"Fraction Shape {df.shape}")
    return df

### A.1. Sanders Analytics Sentiment-labelled tweets

In [56]:
df_1 = load_dataset(
    filepath=dataset_path / 'Sanders Analytics Sentiment-labelled tweets' / 'full-corpus.csv'
)

Shape (5113, 5)

,Topic,Sentiment,TweetId,TweetDate,TweetText
0,apple,positive,126415614616154112,Tue Oct 18 21:53:25 +0000 2011,Now all @Apple has to do is get swype on the i...
1,apple,positive,126404574230740992,Tue Oct 18 21:09:33 +0000 2011,@Apple will be adding more carrier support to ...
2,apple,positive,126402758403305474,Tue Oct 18 21:02:20 +0000 2011,Hilarious @youtube video - guy does a duet wit...
3,apple,positive,126397179614068736,Tue Oct 18 20:40:10 +0000 2011,@RIM you made it too easy for me to switch to ...
4,apple,positive,126395626979196928,Tue Oct 18 20:34:00 +0000 2011,I just realized that the reason I got into twi...

### A.2. 2015-new-years-resolutions

In [41]:
df_2 = load_dataset(
    filepath=dataset_path / '2015-new-years-resolutions' / 'New-years-resolutions-DFE.csv',
    encoding='latin-1'
)

Shape (5011, 15)

,other_topic,resolution_topics,gender,name,Resolution_Category,retweet_count,text,tweet_coord,tweet_created,tweet_date,tweet_id,tweet_location,tweet_state,user_timezone,tweet_region
0,"Read moore books, read less facebook.",Eat healthier,female,Dena_Marina,Health & Fitness,0.0,"#NewYearsResolution :: Read more books, No scr...",NaN,12/31/14 10:48,12/31/14,5.503630e+17,Southern California,CA,Pacific Time (US & Canada),West
1,NaN,Humor about Personal Growth and Interests Reso...,female,ninjagirl325,Humor,1.0,#NewYearsResolution Finally master @ZJ10 's pa...,NaN,12/31/14 10:47,12/31/14,5.503630e+17,New Jersey,NJ,Central Time (US & Canada),Northeast
2,NaN,Be More Confident,male,RickyDelReyy,Personal Growth,0.0,#NewYearsResolution to stop being so damn perf...,NaN,12/31/14 10:46,12/31/14,5.503620e+17,Hollywood,CA,Eastern Time (US & Canada),West
3,Help More\nspread pet therapy|helping other,Other,male,CalmareNJ,Philanthropic,0.0,My #NewYearsResolution is to help my disabled ...,NaN,12/31/14 10:45,12/31/14,5.503620e+17,Metro NYC,NY,NaN,Northeast
4,NaN,Be more positive,female,welovatoyoudemi,Personal Growth,0.0,#NewYearsResolution #2015Goals #2015bucketlist...,NaN,12/31/14 10:44,12/31/14,5.503620e+17,"Pittsburgh, Pennsylvania",PA,Eastern Time (US & Canada),Northeast

### A.3. Depression: Twitter Dataset + Feature Extraction

In [42]:
df_3 = load_dataset(
    filepath=dataset_path / 'Depression - Twitter Dataset + Feature Extraction' / 'Mental-Health-Twitter.csv',
)

Shape (20000, 11)

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1

### A.4. Customer Support on Twitter

In [51]:
# df_4 = load_dataset(
#     filepath=dataset_path / 'Customer Support on Twitter' / 'sample.csv',
# )
df_4 = load_dataset(
    filepath=dataset_path / 'Customer Support on Twitter' / 'twcs' / 'twcs.csv',
)

Shape (2811774, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

### A.5. Twitter Sentiment Dataset

In [44]:
df_5 = load_dataset(
    filepath=dataset_path / 'Twitter Sentiments Dataset' / 'Twitter_Data.csv',
)

Shape (162980, 2)

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

### A.6. Twitter Toxic Tweets

In [45]:
df_6 = load_dataset(
    filepath=dataset_path / 'Twitter Toxic Tweets' / 'twitter_toxic_tweets.csv',
)

Shape (31962, 3)

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

### A.7. Sentiment140
Large dataset

In [47]:
df_6 = load_dataset(
    filepath=dataset_path / 'Sentiment140' / 'training.1600000.processed.noemoticon.csv',
    encoding='latin-1',
)

Shape (1599999, 6)

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

### A.8. twitter_cikm_2010

In [63]:
headers=['UserID', 'TweetID', 'Tweet', 'CreatedAt']

# FULL DATASET
test_filepath = dataset_path / 'twitter_cikm_2010' / 'test_set_tweets.txt'
train_filepath = dataset_path / 'twitter_cikm_2010' / 'training_set_tweets.txt'

# # SAMPLE DATASET
# test_filepath = dataset_path / 'twitter_cikm_2010' / 'test_set_tweets_sample.txt'
# train_filepath = dataset_path / 'twitter_cikm_2010' / 'training_set_tweets_sample.txt'

In [67]:
df_8_test = load_dataset(
    filepath=test_filepath,
    sep='\t',
    headers=headers,
)

Shape (5135949, 4)

,UserID,TweetID,Tweet,CreatedAt
0,22077441,10538487904,Ok today I have to find something to wear for ...,2010-03-15 17:35:58
1,22077441,10536835844,I am glad I'm having this show but I can't wai...,2010-03-15 16:53:44
2,22077441,10536809086,Honestly I don't even know what's going on any...,2010-03-15 16:52:59
3,22077441,10534149786,@LovelyJ_Janelle hey sorry I'm sitting infront...,2010-03-15 15:42:07
4,22077441,10530203659,Sitting infront of this sewing machine ... I d...,2010-03-15 13:55:22

In [68]:
df_8_train = load_dataset(
    filepath=train_filepath,
    sep='\t',
    headers=headers,
)

Shape (3807585, 4)

/var/folders/yh/9qq7z2f14f14bdj_1k2673700000gn/T/ipykernel_40306/2829430374.py:10: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath, sep=sep, encoding=encoding, names=headers if headers else None, on_bad_lines='skip')

,UserID,TweetID,Tweet,CreatedAt
0,60730027,6320951896,@thediscovietnam coo. thanks. just dropped yo...,2009-12-03 18:41:07
1,60730027,6320673258,@thediscovietnam shit it ain't lettin me DM yo...,2009-12-03 18:31:01
2,60730027,6319871652,"@thediscovietnam hey cody, quick question...ca...",2009-12-03 18:01:51
3,60730027,6318151501,@smokinvinyl dang. you need anything? I got ...,2009-12-03 17:00:16
4,60730027,6317932721,"maybe i'm late in the game on this one, but th...",2009-12-03 16:52:36

### A.9. Sentiment of Climate Change

In [48]:
df_9 = load_dataset(
    filepath=dataset_path / 'Sentiment of Climate Change' / '1377884570_tweet_global_warming.csv',
)

Shape (6090, 3)

,tweet,existence,existence.confidence
0,Global warming report urges governments to act...,Yes,1.0000
1,Fighting poverty and global warming in Africa ...,Yes,1.0000
2,Carbon offsets: How a Vatican forest failed to...,Yes,0.8786
3,Carbon offsets: How a Vatican forest failed to...,Yes,1.0000
4,URUGUAY: Tools Needed for Those Most Vulnerabl...,Yes,0.8087

### A.10. Twitter Climate Change Sentiment Dataset

In [49]:
df_10 = load_dataset(
    filepath=dataset_path / 'Twitter Climate Change Sentiment Dataset' / 'twitter_sentiment_data.csv',
)

Shape (43943, 3)

,sentiment,message,tweetid
0,-1,@tiniebeany climate change is an interesting h...,792927353886371840
1,1,RT @NatGeoChannel: Watch #BeforeTheFlood right...,793124211518832641
2,1,Fabulous! Leonardo #DiCaprio's film on #climat...,793124402388832256
3,1,RT @Mick_Fanning: Just watched this amazing do...,793124635873275904
4,2,"RT @cnalive: Pranita Biswasi, a Lutheran from ...",793125156185137153

### A.11. Weather sentiment evaluated

In [50]:
df_11 = load_dataset(
    filepath=dataset_path / 'Weather sentiment evaluated' / 'weather-evaluated-agg-DFE.csv',
)

Shape (1000, 18)

,_unit_id,_golden,_canary,_unit_state,_trusted_judgments,_last_judgment_at,is_the_category_correct_for_this_tweet,is_the_category_correct_for_this_tweet:confidence,orig__canary,orig__last_judgment_at,orig__trusted_judgments,orig__unit_id,orig__unit_state,gold_answer,sentiment,tweet_id,tweet_text,what_emotion_does_the_author_express_specifically_about_the_weatherconfidence
0,315120690,True,NaN,golden,98,NaN,Yes,1.0000,NaN,8/24/13 0:21,20,1,finalized,Yes,Positive,81990560,Grilling kabobs on the grill last night was am...,0.8439
1,315120691,True,NaN,golden,78,NaN,Yes,1.0000,NaN,8/24/13 0:49,20,1,finalized,Yes,Negative,84314377,The slowest day ever !! And the weather makes ...,0.6963
2,315120692,True,NaN,golden,62,NaN,Yes,1.0000,NaN,8/24/13 0:55,20,1,finalized,Yes,Neutral / author is just sharing information,82846118,Fire Weather Watch issued May 17 at 4:21PM CDT...,0.8802
3,315120693,True,NaN,golden,68,NaN,Yes,1.0000,NaN,8/24/13 0:48,20,1,finalized,Yes,Positive,82843785,Im going to lunch early today. The weather i...,0.6897
4,315120694,True,NaN,golden,64,NaN,Yes,0.9239,NaN,8/24/13 1:19,20,1,finalized,Yes,Neutral / author is just sharing information,82840144,Weekend Weather Causes Delays In I-270 Bridge ...,0.6153

## B. Unified all Dataset

### B.1. Merge