# ISCRAM2013

Joplin 2011

---

## A. Original description

#### Meta Information:

- We used paid workers from the Crowdflower crowdsourcing platform for labeling
- At least three different workers were required to agree on a label before a task is finalized
- We ran two tasks (as described below) for labeling


####  Task # 1 Categories---Description:

1. Personal Only---if a message is only of interest to its author and her immediate circle of family/friends and does not convey any useful information to other people who do not know the author.
2. Informative (Direct)--- if the message is of interest to other people beyond the author's immediate circle, and seems to be written by a person who is a direct eyewitness of what is taking place.
3. Informative (Indirect)--- if the message is of interest to other people beyond the author's immediate circle, and seems to be seen/heard by the person on the radio, TV, newspaper, or other source. The message must specify the source.
4. Informative (Direct or Indirect)--- if the message is of interest to other people beyond the author's immediate circle, but there is not enough information to tell if it is a direct report or a repetition of something from another source.
5. Other--- if the message is not in English, or if it cannot be classified.


####  Task # 2 Categories---Description:

1. Caution and advice---if a message conveys/reports information about some warning or a piece of advice about a possible hazard of an incident.
2. Casualties and damage---if a message reports the information about casualties or damage done by an incident.
3. Donations of money, goods or services---if a message speaks about money raised, donation offers, goods/services offered or asked by the victims of an incident.
4. People missing, found, or seen---if a message reports about the missing or found person effected by an incident or seen a celebrity visit on ground zero.
5. Information source---if a message conveys/contains some information sources like photo, footage, video, or mentions other sources like TV, radio related to an incident.

#### Reference

Muhammad Imran, Shady Elbassuoni, Carlos Castillo, Fernando Diaz and Patrick Meier. Extracting Information Nuggets from Disaster-Related Messages in Social Media. In Proc. of the 10th International Conference on Information Systems for Crisis Response and Management (ISCRAM), May 2013, Baden-Baden, Germany.

## B. Overview

In [2]:
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
datasets_path = Path(os.getenv("DATASETS_PATH")) / "Datasets"

In [3]:
import pandas as pd

dataset_path = datasets_path / 'ISCRAM2013' / 'ISCRAM2013_dataset' / 'Joplin_2011_labeled_data'

files = [
    '01_personal-informative-other/a131709.csv',
    '02_informative_caution-infosrc-donation-damage-other/a121571.csv',
    '03_caution-n-advice_classify-extract/a122047.csv',
    '03_damage-n-casualties_classify-extract/a126730.csv',
    '03_donation-help_classify-extract/a126728.csv',
    '03_infosrc_classify-extract/a122582.csv',
]

### Task 1

In [4]:
filepath = dataset_path / files[0]

if not filepath.exists():
    raise FileNotFoundError(f'Not found: {filepath}')

df_t1 = pd.read_csv(filepath)
df_t1.columns = df_t1.columns.str.strip()

In [5]:
df_t1.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,predicted,text_no_rt,tweet
0,204690712,False,finalized,4,10/6/2012 03:35:03,Informative (Direct or Indirect),0.5133,NaN,Informative (Indirect),Cruuuuud. Tornado warning for Denton County. A...,Cruuuuud. Tornado warning for Denton County. A...
1,204690713,True,golden,129,10/6/2012 03:25:33,Informative (Indirect),0.4781,Informative (Indirect),Informative (Indirect),Tornado WARNING for Tarrant county. Storm spot...,Tornado WARNING for Tarrant county. Storm spot...
2,204690714,False,finalized,6,10/5/2012 09:43:16,Informative (Direct or Indirect),1.0000,NaN,Informative (Indirect),Tornado on the ground in Azle headed right tow...,RT @AmandaSalinas: Tornado on the ground in Az...
3,204690715,True,golden,125,10/6/2012 03:25:33,Informative (Indirect),0.6346,Informative (Indirect),Informative (Indirect),US tornado toll rises to 122 (AFP) http://dlvr...,US tornado toll rises to 122 (AFP) http://dlvr...
4,204690716,False,finalized,3,10/6/2012 03:02:15,Informative (Indirect),1.0000,NaN,Informative (Indirect),US tornado toll rises to 122 (AFP) http://dlvr...,US tornado toll rises to 122 (AFP) http://dlvr...

In [6]:
csv_array = df_t1.values

print(f'Loaded {len(df_t1)} rows from: {filepath}')
print(csv_array[:5])

Loaded 2384 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/ISCRAM2013/ISCRAM2013_dataset/Joplin_2011_labeled_data/01_personal-informative-other/a131709.csv
[[204690712 False 'finalized' 4 '10/6/2012 03:35:03'
  'Informative (Direct or Indirect)' 0.5133 nan 'Informative (Indirect)'
  "Cruuuuud. Tornado warning for Denton County. And the TV isn't working. And the Dallas news sites aren't helpful. Cruuuuud."
  "Cruuuuud. Tornado warning for Denton County. And the TV isn't working. And the Dallas news sites aren't helpful. Cruuuuud."]
 [204690713 True 'golden' 129 '10/6/2012 03:25:33'
  'Informative (Indirect)' 0.4781 'Informative (Indirect)'
  'Informative (Indirect)'
  'Tornado WARNING for Tarrant county. Storm spotters were reporting a funnel cloud but the heavy rain has wrapped around the suspected area.'
  'Tornado WARNING for Tarrant county. Storm spotters were reporting a funnel cloud but the heavy rain has wrapped around the suspected area.']
 [204690714 False 'finalized' 6 '10/5/2012 09:43:16'
  'Informative (Direct or Indirect)' 1.0 nan 'Informative (Indirect)'
  'Tornado on the ground in Azle headed right toward TMS'
  'RT @AmandaSalinas: Tornado on the ground in Azle headed right toward TMS']
 [204690715 True 'golden' 125 '10/6/2012 03:25:33'
  'Informative (Indirect)' 0.6346 'Informative (Indirect)'
  'Informative (Indirect)'
  'US tornado toll rises to 122 (AFP) http://dlvr.it/StLMD'
  'US tornado toll rises to 122 (AFP) http://dlvr.it/StLMD']
 [204690716 False 'finalized' 3 '10/6/2012 03:02:15'
  'Informative (Indirect)' 1.0 nan 'Informative (Indirect)'
  'US tornado toll rises to 122 (AFP) http://dlvr.it/StLMh'
  'US tornado toll rises to 122 (AFP) http://dlvr.it/StLMh']]

In [ ]:
print(len(df_t1[df_t1['_golden'] == True]))
print(len(df_t1[df_t1['_unit_state'] == 'golden']))

78
78

In [9]:
df_t1_nongolden = df_t1[df_t1['_golden'] == False]
print(df_t1_nongolden['choose_one'].value_counts())
print(len(df_t1_nongolden))

choose_one
Personal only                       779
Informative (Direct or Indirect)    737
Informative (Indirect)              444
Informative (Direct)                261
Other                                85
Name: count, dtype: int64
2306

In [ ]:
# count the number of rows in the 'choose_one' column that contains the value 'Informative'
df_t1[df_t1['_golden'] == False]['choose_one'].str.contains('Informative').sum()

np.int64(1442)

### Task 2

In [ ]:
filepath = dataset_path / files[1]

if not filepath.exists():
    raise FileNotFoundError(f'Not found: {filepath}')

df_t2 = pd.read_csv(filepath)
df_t2.columns = df_t2.columns.str.strip()

In [ ]:
df_t2.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,id,retweetcount,screenname,text,userid
0,191082764,False,finalized,3,8/12/2012 13:24:55,Caution and advice,1.0000,NaN,74943468706873200,0.0,1stJoshRobinson,Yesterday was supposed to be 70 and sunny/cold...,85940638.0
1,191082765,False,finalized,4,8/12/2012 13:38:35,Information source,0.4896,NaN,74301096193040304,0.0,jenr8rluvsJesus,@fox12weather re: tornado. I live in Vancouver...,46529360.0
2,191082766,False,finalized,3,8/12/2012 13:29:09,"Donations of money, goods or services",1.0000,NaN,77764430137536400,1.0,ABC_Plastics,@TippingPointSEO: please follow my friends @R...,145273867.0
3,191082767,False,finalized,3,8/12/2012 13:36:39,Casualties and damage,1.0000,NaN,77449750374395904,2.0,IvanTheTurrible,"My house was blown away by a tornado, but a fa...",33371804.0
4,191082768,False,finalized,3,8/12/2012 13:11:03,Caution and advice,0.6423,NaN,76134461049274304,0.0,BadAssNigerian,@Juss2Live: News was goin crazy about tornado...,50420551.0

In [ ]:
df_t2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1233 entries, 0 to 1232
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _unit_id               1233 non-null   int64
 1   _golden                1233 non-null   bool
 2   _unit_state            1233 non-null   object
 3   _trusted_judgments     1233 non-null   int64
 4   _last_judgment_at      1233 non-null   object
 5   choose_one             1233 non-null   object
 6   choose_one:confidence  1233 non-null   float64
 7   choose_one_gold        62 non-null     object
 8   id                     1233 non-null   int64
 9   retweetcount           649 non-null    float64
 10  screenname             1221 non-null   object
 11  text                   1233 non-null   object
 12  userid                 1221 non-null   float64
dtypes: bool(1), float64(3), int64(3), object(6)
memory usage: 116.9+ KB

In [ ]:
# find the rows in df_t1 that have a '_unit_id' that is not in df_t2
# df_t1[~df_t1['_unit_id'].isin(df_t2['_unit_id'])]
id1 = df_t1['_unit_id'].astype(str).str.strip().str.replace(r"\.0$", "", regex=True)
id2 = df_t2['_unit_id'].astype(str).str.strip().str.replace(r"\.0$", "", regex=True)

mask_not_in_t2 = ~id1.isin(set(id2))
print("not in t2:", mask_not_in_t2.sum(), "out of", len(mask_not_in_t2))

print("not in t2:", len(df_t1[mask_not_in_t2]))

not in t2: 2384 out of 2384
not in t2: 2384